### ISSUE TITLE
Fetcher enhancement for mCloud downloads

### ISSUE THREAD

**Issue by IVIerle** [dice-group/Squirrel#50]
For future reference, not urgent: 

Extensions of **current Fetchers**:
- [ ] Test and verify that FTPFetcher can deal with nested directories

Introduction of **new Fetchers**: 
Implement new Fetchers which can deal with (at least the most common) APIs on mCloud and query and store the datasets
- [ ] WMS
- [ ] WFS
- [ ] Atom Feed
- [ ] ...

**Comment by MichaelRoeder** [comment]
@gsjunior86 Please concentrate on the testing of the FTPFetcher and extend it to be able to recursively download a directory.

**Comment by gsjunior86** [comment]
@MichaelRoeder , the fetch method from the FTPFetcher now can return a directory where all fetched files were stored. Instead of creating a new fetch method in the Fetcher interface (obliging all the other fetchers that won't get multiple files to implement it), i wrote a check in the Worker that ensures if the file is a dir or not. If it is, will iterate over all files present in the temp dir
