### ISSUE TITLE
Improve RDFAnalyzer

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#56]
atm RDFAnalyzer uses two strategies to infer RDF serialization: by mimetype and by filename. From the last Squirrel run I can see a lot of errors (fails to detect ttl serialization).

TODOs:
* [x] add bunch of small RDF files to resource folder for testing in all possible serializations (ttl, nt, rdfxml, n3, quads). Also include some German language RDF there.
* [x] run current implementation of RDFAnalyzer over that data, check precision
* [x] implement heuristic to determine serialization from first N bytes of data (maybe there is something like this alreade implemented in Jena)

**Comment by gsjunior86** [comment]
@MichaelRoeder , the solution to define Jena Language was no efficient, since Jena does not recognize properly the Lang based on the mime type detected by the first N bytes.  Ex : an application/text detection could it be N-Triples, N-Quads, JsonLD, rdf/Json and so on.

So, i have made the option to try it by brute force, testing the Langs availables (excluding redundant ones)

**Comment by RicardoUsbeck** [comment]
Just my two cents w.r.t. to the first N bytes: Train a small classifier with https://www.cs.waikato.ac.nz/ml/weka/ ? Did you try or shall we outsource this?
